/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FuncoesRouteImport } from './routes/funcoes'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAgendaRouteImport } from './routes/_authenticated/painel.agenda'
import { Route as AuthenticatedPainelCampanhasRouteImport } from './routes/_authenticated/painel.campanhas'
import { Route as AuthenticatedPainelConexoesRouteImport } from './routes/_authenticated/painel.conexoes'
import { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated/painel.configuracoes'
import { Route as AuthenticatedPainelContatosRouteImport } from './routes/_authenticated/painel.contatos'
import { Route as AuthenticatedPainelConversasRouteImport } from './routes/_authenticated/painel.conversas'
import { Route as AuthenticatedPainelCrmRouteImport } from './routes/_authenticated/painel.crm'
import { Route as AuthenticatedPainelFunisRouteImport } from './routes/_authenticated/painel.funis'
import { Route as AuthenticatedPainelIaRouteImport } from './routes/_authenticated/painel.ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncoesRoute = FuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAgendaRoute =
  AuthenticatedPainelAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCampanhasRoute =
  AuthenticatedPainelCampanhasRouteImport.update({
    id: '/campanhas',
    path: '/campanhas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConexoesRoute =
  AuthenticatedPainelConexoesRouteImport.update({
    id: '/conexoes',
    path: '/conexoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConfiguracoesRoute =
  AuthenticatedPainelConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelContatosRoute =
  AuthenticatedPainelContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConversasRoute =
  AuthenticatedPainelConversasRouteImport.update({
    id: '/conversas',
    path: '/conversas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCrmRoute = AuthenticatedPainelCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelFunisRoute =
  AuthenticatedPainelFunisRouteImport.update({
    id: '/funis',
    path: '/funis',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelIaRoute = AuthenticatedPainelIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/planos': typeof PlanosRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/painel/campanhas': typeof AuthenticatedPainelCampanhasRoute
  '/painel/conexoes': typeof AuthenticatedPainelConexoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/contatos': typeof AuthenticatedPainelContatosRoute
  '/painel/conversas': typeof AuthenticatedPainelConversasRoute
  '/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/painel/funis': typeof AuthenticatedPainelFunisRoute
  '/painel/ia': typeof AuthenticatedPainelIaRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/planos': typeof PlanosRoute
  '/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/painel/campanhas': typeof AuthenticatedPainelCampanhasRoute
  '/painel/conexoes': typeof AuthenticatedPainelConexoesRoute
  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/painel/contatos': typeof AuthenticatedPainelContatosRoute
  '/painel/conversas': typeof AuthenticatedPainelConversasRoute
  '/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/painel/funis': typeof AuthenticatedPainelFunisRoute
  '/painel/ia': typeof AuthenticatedPainelIaRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/funcoes': typeof FuncoesRoute
  '/integracoes': typeof IntegracoesRoute
  '/planos': typeof PlanosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/painel/agenda': typeof AuthenticatedPainelAgendaRoute
  '/_authenticated/painel/campanhas': typeof AuthenticatedPainelCampanhasRoute
  '/_authenticated/painel/conexoes': typeof AuthenticatedPainelConexoesRoute
  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
  '/_authenticated/painel/contatos': typeof AuthenticatedPainelContatosRoute
  '/_authenticated/painel/conversas': typeof AuthenticatedPainelConversasRoute
  '/_authenticated/painel/crm': typeof AuthenticatedPainelCrmRoute
  '/_authenticated/painel/funis': typeof AuthenticatedPainelFunisRoute
  '/_authenticated/painel/ia': typeof AuthenticatedPainelIaRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/funcoes'
    | '/integracoes'
    | '/planos'
    | '/painel'
    | '/painel/agenda'
    | '/painel/campanhas'
    | '/painel/conexoes'
    | '/painel/configuracoes'
    | '/painel/contatos'
    | '/painel/conversas'
    | '/painel/crm'
    | '/painel/funis'
    | '/painel/ia'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/funcoes'
    | '/integracoes'
    | '/planos'
    | '/painel/agenda'
    | '/painel/campanhas'
    | '/painel/conexoes'
    | '/painel/configuracoes'
    | '/painel/contatos'
    | '/painel/conversas'
    | '/painel/crm'
    | '/painel/funis'
    | '/painel/ia'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/faq'
    | '/funcoes'
    | '/integracoes'
    | '/planos'
    | '/_authenticated/painel'
    | '/_authenticated/painel/agenda'
    | '/_authenticated/painel/campanhas'
    | '/_authenticated/painel/conexoes'
    | '/_authenticated/painel/configuracoes'
    | '/_authenticated/painel/contatos'
    | '/_authenticated/painel/conversas'
    | '/_authenticated/painel/crm'
    | '/_authenticated/painel/funis'
    | '/_authenticated/painel/ia'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  FuncoesRoute: typeof FuncoesRoute
  IntegracoesRoute: typeof IntegracoesRoute
  PlanosRoute: typeof PlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcoes': {
      id: '/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof FuncoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/agenda': {
      id: '/_authenticated/painel/agenda'
      path: '/agenda'
      fullPath: '/painel/agenda'
      preLoaderRoute: typeof AuthenticatedPainelAgendaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/campanhas': {
      id: '/_authenticated/painel/campanhas'
      path: '/campanhas'
      fullPath: '/painel/campanhas'
      preLoaderRoute: typeof AuthenticatedPainelCampanhasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/conexoes': {
      id: '/_authenticated/painel/conexoes'
      path: '/conexoes'
      fullPath: '/painel/conexoes'
      preLoaderRoute: typeof AuthenticatedPainelConexoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/configuracoes': {
      id: '/_authenticated/painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/contatos': {
      id: '/_authenticated/painel/contatos'
      path: '/contatos'
      fullPath: '/painel/contatos'
      preLoaderRoute: typeof AuthenticatedPainelContatosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/conversas': {
      id: '/_authenticated/painel/conversas'
      path: '/conversas'
      fullPath: '/painel/conversas'
      preLoaderRoute: typeof AuthenticatedPainelConversasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/crm': {
      id: '/_authenticated/painel/crm'
      path: '/crm'
      fullPath: '/painel/crm'
      preLoaderRoute: typeof AuthenticatedPainelCrmRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/funis': {
      id: '/_authenticated/painel/funis'
      path: '/funis'
      fullPath: '/painel/funis'
      preLoaderRoute: typeof AuthenticatedPainelFunisRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/ia': {
      id: '/_authenticated/painel/ia'
      path: '/ia'
      fullPath: '/painel/ia'
      preLoaderRoute: typeof AuthenticatedPainelIaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAgendaRoute: typeof AuthenticatedPainelAgendaRoute
  AuthenticatedPainelCampanhasRoute: typeof AuthenticatedPainelCampanhasRoute
  AuthenticatedPainelConexoesRoute: typeof AuthenticatedPainelConexoesRoute
  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
  AuthenticatedPainelContatosRoute: typeof AuthenticatedPainelContatosRoute
  AuthenticatedPainelConversasRoute: typeof AuthenticatedPainelConversasRoute
  AuthenticatedPainelCrmRoute: typeof AuthenticatedPainelCrmRoute
  AuthenticatedPainelFunisRoute: typeof AuthenticatedPainelFunisRoute
  AuthenticatedPainelIaRoute: typeof AuthenticatedPainelIaRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAgendaRoute: AuthenticatedPainelAgendaRoute,
  AuthenticatedPainelCampanhasRoute: AuthenticatedPainelCampanhasRoute,
  AuthenticatedPainelConexoesRoute: AuthenticatedPainelConexoesRoute,
  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
  AuthenticatedPainelContatosRoute: AuthenticatedPainelContatosRoute,
  AuthenticatedPainelConversasRoute: AuthenticatedPainelConversasRoute,
  AuthenticatedPainelCrmRoute: AuthenticatedPainelCrmRoute,
  AuthenticatedPainelFunisRoute: AuthenticatedPainelFunisRoute,
  AuthenticatedPainelIaRoute: AuthenticatedPainelIaRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  FuncoesRoute: FuncoesRoute,
  IntegracoesRoute: IntegracoesRoute,
  PlanosRoute: PlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
